export type TalentPoolCategory = 'general' | 'department' | 'event'

/** Event pools can expose a public application form. */
export type TalentPoolFormStatus = 'live' | 'draft'

export type PoolCandidateStage
  = 'New' | 'Applied' | 'Screened' | 'Interview' | 'Offer' | 'Reference check'

export interface TalentPool {
  id: string
  name: string
  description: string
  category: TalentPoolCategory
  /** Set when category is 'department'. */
  department?: string
  /** Set when category is 'event'. */
  event?: string
  /**
   * System pools are generated by the product, not by a user — currently only the
   * General Application pool. They cannot be renamed, archived or deleted.
   */
  system?: boolean
  total: number
  /** ISO date, e.g. '2026-04-12'. */
  created: string
  /** TeamMember ids — resolved through useTeam(). */
  members: string[]
  archived: boolean
  /** Pinned pools sort above the rest within their tab. */
  pinned: boolean
  formStatus?: TalentPoolFormStatus
}

export interface PoolCandidate {
  id: string
  poolId: string
  name: string
  stage: PoolCandidateStage
  /** Free text — 'Referral', 'Career Site', 'LinkedIn', 'Event Form', 'General Application'. */
  appliedVia: string
  jobTitle: string | null
  email: string
  phone: string | null
  location: string
  /** 0–100, or null when the candidate has not been scored. */
  aiScore: number | null
  evalScore: number | null
  tags: string[]
  /** ISO date the candidate entered the pool. */
  date: string
}

export interface TalentPoolsResponse {
  pools: TalentPool[]
  candidates: PoolCandidate[]
}
